INSTALLARE DOCKER DESKTOP ED ESEGUIRE IL FILE "run.bat"
QUANDO FINISCI DI LAVORARCI E VUOI FAR ALTRO ESEGUI "shutdown.bat"
ALTRIMENTI DOCKER CONTINUERÀ A MANGIARTI CPU E RAM
cognomepartecipante1+_cognomeparticapante2_progetto-finale.zip